//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignInventory
    {
        public long AssignInventoryID { get; set; }
        public long InventoryID { get; set; }
        public long AssignedUserID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public long IssuedBy { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<long> AssginedQuantity { get; set; }
    
        public virtual InventoryMaster InventoryMaster { get; set; }
    }
}
