//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DARDetail
    {
        public DARDetail()
        {
            this.eFleetFuelings = new HashSet<eFleetFueling>();
        }
    
        public long DARId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public string ActivityDetails { get; set; }
        public bool IsManual { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public long TaskType { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string StartTimeImage { get; set; }
        public string EndTimeImage { get; set; }
        public string UserName { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContact { get; set; }
        public string VehicleColor { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public Nullable<int> VehicleYear { get; set; }
        public string DriverLicenseNo { get; set; }
        public string CurrentLocation { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string StateId { get; set; }
        public string ZipCode { get; set; }
        public string LicensePlateNo { get; set; }
        public string ProjectDesc { get; set; }
        public string EmpSignatureImage { get; set; }
        public string CustomerSignatureImage { get; set; }
        public string DisclaimerFormFile { get; set; }
    
        public virtual ICollection<eFleetFueling> eFleetFuelings { get; set; }
    }
}
