//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECashPaymentDetail
    {
        public long PaymentId { get; set; }
        public string ItemName { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public long ParentId { get; set; }
    }
}
