//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECashTransaction
    {
        public long ECashId { get; set; }
        public Nullable<long> DriverId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public int Category { get; set; }
        public string CompanyInformation { get; set; }
        public string DriverName { get; set; }
        public string SpecialNotes { get; set; }
        public decimal Amount { get; set; }
        public string ModeOfPayment { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual VehicleRegistration VehicleRegistration { get; set; }
        public virtual VehicleRegistration VehicleRegistration1 { get; set; }
    }
}
