//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECashTransactionCategory
    {
        public long ECashTransactionCategoryId { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public long LOCATIONID { get; set; }
        public long GlobalCodeId { get; set; }
    
        public virtual GlobalCode GlobalCode { get; set; }
    }
}
