//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eFleetPreventativeMaintenance
    {
        public eFleetPreventativeMaintenance()
        {
            this.eFleetMaintenances = new HashSet<eFleetMaintenance>();
        }
    
        public long ID { get; set; }
        public long VehicleID { get; set; }
        public string VehicleNumber { get; set; }
        public string QRCodeID { get; set; }
        public long LocationID { get; set; }
        public Nullable<long> Meter { get; set; }
        public Nullable<long> ReminderMetric { get; set; }
        public string ReminderMetricDesc { get; set; }
        public Nullable<int> OtherMilesComment { get; set; }
        public Nullable<long> Category { get; set; }
        public string OtherComment { get; set; }
        public Nullable<System.DateTime> ServiceDueDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<long> CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string MaintenanceDesc { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual eFleetVehicle eFleetVehicle { get; set; }
        public virtual ICollection<eFleetMaintenance> eFleetMaintenances { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
        public virtual UserRegistration UserRegistration1 { get; set; }
    }
}
