//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class eFleetPassengerTrackingRoute
    {
        public eFleetPassengerTrackingRoute()
        {
            this.eFleetPassengerTrackingCounts = new HashSet<eFleetPassengerTrackingCount>();
        }
    
        public long RouteID { get; set; }
        public long ServiceType { get; set; }
        public string RouteName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<long> LocationID { get; set; }
        public string PickUpPoint { get; set; }
        public string DropPoint { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual ICollection<eFleetPassengerTrackingCount> eFleetPassengerTrackingCounts { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
