//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public long EmailLogId { get; set; }
        public Nullable<long> SentBy { get; set; }
        public Nullable<long> SentTo { get; set; }
        public string SentEmail { get; set; }
        public string Subject { get; set; }
        public Nullable<long> LocationId { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool isForgot { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
    }
}
