//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMaintenanceSurvey
    {
        public long SurveyId { get; set; }
        public Nullable<long> GlobalCodeId { get; set; }
        public int Answer { get; set; }
        public Nullable<long> SubmittedBy { get; set; }
        public Nullable<long> LocationId { get; set; }
        public string IfNoThenDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> WorkOrderAssignmentId { get; set; }
    
        public virtual GlobalCode GlobalCode { get; set; }
    }
}
