//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public long ExceptionId { get; set; }
        public string InnerExceptionMessage { get; set; }
        public string Message { get; set; }
        public string methodName { get; set; }
        public string GetBaseException { get; set; }
        public string GetHashCode { get; set; }
        public string Type { get; set; }
        public System.DateTime createdDate { get; set; }
        public string Parameters { get; set; }
    }
}
