//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infraction
    {
        public Infraction()
        {
            this.InfractionLevelDetails = new HashSet<InfractionLevelDetail>();
        }
    
        public long InfractionId { get; set; }
        public long QRCID { get; set; }
        public long VehicleId { get; set; }
        public string Operation { get; set; }
        public Nullable<bool> IsCheckIn { get; set; }
        public Nullable<long> InfractionType { get; set; }
        public string Remarks { get; set; }
        public string EnforcementImage { get; set; }
        public long LocationId { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual ICollection<InfractionLevelDetail> InfractionLevelDetails { get; set; }
        public virtual VehicleRegistration VehicleRegistration { get; set; }
        public virtual QRCMaster QRCMaster { get; set; }
    }
}
