//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationMaster
    {
        public LocationMaster()
        {
            this.AdminLocationMappings = new HashSet<AdminLocationMapping>();
            this.EmailLogs = new HashSet<EmailLog>();
            this.EmployeeLocationMappings = new HashSet<EmployeeLocationMapping>();
            this.InventoryMasters = new HashSet<InventoryMaster>();
            this.LocationClientMappings = new HashSet<LocationClientMapping>();
            this.LocationServices = new HashSet<LocationService>();
            this.LoginLogs = new HashSet<LoginLog>();
            this.ManagerLocationMappings = new HashSet<ManagerLocationMapping>();
            this.LoginLogs1 = new HashSet<LoginLog>();
            this.QRCScanLogs = new HashSet<QRCScanLog>();
            this.QRCMasters = new HashSet<QRCMaster>();
            this.WorkRequestAssignments = new HashSet<WorkRequestAssignment>();
            this.eFleetVehicleScanLogs = new HashSet<eFleetVehicleScanLog>();
            this.eFleetFuelings = new HashSet<eFleetFueling>();
            this.eFleetPreventativeMaintenances = new HashSet<eFleetPreventativeMaintenance>();
            this.eFleetVehicles = new HashSet<eFleetVehicle>();
            this.eFleetDrivers = new HashSet<eFleetDriver>();
            this.eFleetMaintenances = new HashSet<eFleetMaintenance>();
            this.eFleetVehicleIncidents = new HashSet<eFleetVehicleIncident>();
        }
    
        public long LocationId { get; set; }
        public string LocationName { get; set; }
        public string Description { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Mobile { get; set; }
        public string PhoneNo { get; set; }
        public string ZipCode { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> QRCID { get; set; }
        public long LocationType { get; set; }
        public Nullable<long> LocationSubType { get; set; }
        public bool IsVerifiedByManager { get; set; }
        public bool IsVerifiedByClient { get; set; }
        public string LocationSubTypeDesc { get; set; }
    
        public virtual ICollection<AdminLocationMapping> AdminLocationMappings { get; set; }
        public virtual ICollection<EmailLog> EmailLogs { get; set; }
        public virtual ICollection<EmployeeLocationMapping> EmployeeLocationMappings { get; set; }
        public virtual ICollection<InventoryMaster> InventoryMasters { get; set; }
        public virtual ICollection<LocationClientMapping> LocationClientMappings { get; set; }
        public virtual ICollection<LocationService> LocationServices { get; set; }
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
        public virtual ICollection<ManagerLocationMapping> ManagerLocationMappings { get; set; }
        public virtual ICollection<LoginLog> LoginLogs1 { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual ICollection<QRCScanLog> QRCScanLogs { get; set; }
        public virtual ICollection<QRCMaster> QRCMasters { get; set; }
        public virtual ICollection<WorkRequestAssignment> WorkRequestAssignments { get; set; }
        public virtual ICollection<eFleetVehicleScanLog> eFleetVehicleScanLogs { get; set; }
        public virtual ICollection<eFleetFueling> eFleetFuelings { get; set; }
        public virtual ICollection<eFleetPreventativeMaintenance> eFleetPreventativeMaintenances { get; set; }
        public virtual ICollection<eFleetVehicle> eFleetVehicles { get; set; }
        public virtual ICollection<eFleetDriver> eFleetDrivers { get; set; }
        public virtual ICollection<eFleetMaintenance> eFleetMaintenances { get; set; }
        public virtual ICollection<eFleetVehicleIncident> eFleetVehicleIncidents { get; set; }
    }
}
