//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitType
    {
        public int PermitTypeId { get; set; }
        public int VendorID { get; set; }
        public string c350_55 { get; set; }
        public string c350_56 { get; set; }
        public string c350_57 { get; set; }
        public string c350_347 { get; set; }
        public string c350_53 { get; set; }
        public string c350_54 { get; set; }
        public string c351_55 { get; set; }
        public string c351_56 { get; set; }
        public string c351_57 { get; set; }
        public string c351_347 { get; set; }
        public string c351_53 { get; set; }
        public string c351_54 { get; set; }
        public string c352_55 { get; set; }
        public string c352_56 { get; set; }
        public string c352_57 { get; set; }
        public string c352_347 { get; set; }
        public string c352_53 { get; set; }
        public string c352_54 { get; set; }
        public string c353_55 { get; set; }
        public string c353_56 { get; set; }
        public string c353_57 { get; set; }
        public string c353_347 { get; set; }
        public string c353_53 { get; set; }
        public string c353_54 { get; set; }
        public string c354_55 { get; set; }
        public string c354_56 { get; set; }
        public string c354_57 { get; set; }
        public string c354_347 { get; set; }
        public string c354_53 { get; set; }
        public string c354_54 { get; set; }
        public string c355_55 { get; set; }
        public string c355_56 { get; set; }
        public string c355_57 { get; set; }
        public string c355_347 { get; set; }
        public string c355_53 { get; set; }
        public string c355_54 { get; set; }
    }
}
