//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZone
    {
        public long TimezoneId { get; set; }
        public Nullable<decimal> TimezoneOffset { get; set; }
        public Nullable<int> ClientTimeOffset { get; set; }
        public string TimezoneName { get; set; }
    }
}
