//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRegistrationAmount
    {
        public long VehicleAmoutID { get; set; }
        public double Amount { get; set; }
        public int MotortypeTypeId { get; set; }
        public int PermitTypeId { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
