//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRegistration
    {
        public VehicleRegistration()
        {
            this.ECashTransactions = new HashSet<ECashTransaction>();
            this.ECashTransactions1 = new HashSet<ECashTransaction>();
            this.Infractions = new HashSet<Infraction>();
            this.WeeklyVehicleChecks = new HashSet<WeeklyVehicleCheck>();
        }
    
        public long VehicleID { get; set; }
        public long QRCID { get; set; }
        public Nullable<long> VendorUserID { get; set; }
        public string CompanyTaxIdNo { get; set; }
        public string AcknowledgementForm { get; set; }
        public string W9Form { get; set; }
        public Nullable<long> FeeFrequency { get; set; }
        public Nullable<long> IsApprovedByManager { get; set; }
        public string ManagerDenialReason { get; set; }
        public Nullable<long> IsApprovedByClient { get; set; }
        public string ClientDenialReason { get; set; }
        public string SpecialNotes { get; set; }
        public Nullable<System.DateTime> PickUpDateTime { get; set; }
        public string VehicleImage { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleIdentificationNo { get; set; }
        public Nullable<long> VehicleType { get; set; }
        public System.DateTime VehicleRegistratoinExpiry { get; set; }
        public string VehicleRegistratoinProofDoc { get; set; }
        public string VehicleTagNo { get; set; }
        public string CityPermitNo { get; set; }
        public Nullable<System.DateTime> CityPermitExpiryDate { get; set; }
        public Nullable<System.DateTime> PermitDuration { get; set; }
        public string DriverName { get; set; }
        public string LicenseNo { get; set; }
        public string DriverProfilePic { get; set; }
        public Nullable<System.DateTime> LicenseExpiryDate { get; set; }
        public string LicenseProofDoc { get; set; }
        public long PermitType { get; set; }
        public string PermitBillingCode { get; set; }
        public string InsurancePlan { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> PolicyExpiration { get; set; }
        public string InsuranceProofDoc { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> PermitDetailsType { get; set; }
        public string VehicleCode { get; set; }
        public Nullable<decimal> PermitTypePrice { get; set; }
    
        public virtual ICollection<ECashTransaction> ECashTransactions { get; set; }
        public virtual ICollection<ECashTransaction> ECashTransactions1 { get; set; }
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual GlobalCode GlobalCode2 { get; set; }
        public virtual GlobalCode GlobalCode3 { get; set; }
        public virtual ICollection<Infraction> Infractions { get; set; }
        public virtual ICollection<WeeklyVehicleCheck> WeeklyVehicleChecks { get; set; }
        public virtual QRCMaster QRCMaster { get; set; }
    }
}
