//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkOrderEMS.Data.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorMaster
    {
        public VendorMaster()
        {
            this.QRCMasters = new HashSet<QRCMaster>();
        }
    
        public long VendorID { get; set; }
        public string CompanyName { get; set; }
        public string DBA { get; set; }
        public string ContactName { get; set; }
        public string ManagerPOC { get; set; }
        public string MobilePOC { get; set; }
        public string BusinessNo { get; set; }
        public string IndustryName { get; set; }
        public string CompanyLogo { get; set; }
        public Nullable<long> CompanySize { get; set; }
        public System.DateTime JoinFrom { get; set; }
        public long UserId { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string POCEmail { get; set; }
        public string OwnerRegisterdAgent { get; set; }
        public Nullable<long> IsApprovedByManager { get; set; }
        public Nullable<long> IsApprovedByClient { get; set; }
        public string TaxIdNumber { get; set; }
        public Nullable<long> LocationId { get; set; }
        public string AcknowledgementForm { get; set; }
        public string W9Form { get; set; }
        public Nullable<System.DateTime> BusinessExpDate { get; set; }
        public Nullable<System.DateTime> StateLicExpDate { get; set; }
        public string DescriptionForDecline { get; set; }
    
        public virtual GlobalCode GlobalCode { get; set; }
        public virtual GlobalCode GlobalCode1 { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
        public virtual ICollection<QRCMaster> QRCMasters { get; set; }
    }
}
